-- Таблица загруженных песен
CREATE TABLE IF NOT EXISTS aikaraoke_songs (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    USER_ID INT(18) NOT NULL,
    ORIGINAL_FILENAME VARCHAR(255) NOT NULL,
    STORAGE_PATH VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) DEFAULT NULL,
    ARTIST VARCHAR(255) DEFAULT NULL,
    DURATION INT(11) DEFAULT NULL,
    STATUS VARCHAR(255) DEFAULT 'uploaded',
    PROCESSING_STARTED TIMESTAMP NULL DEFAULT NULL,
    PROCESSING_COMPLETED TIMESTAMP NULL DEFAULT NULL,
    DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX IX_AIKARAOKE_USER_ID (USER_ID),
    INDEX IX_AIKARAOKE_STATUS (STATUS)
);

-- Таблица результатов обработки песен
CREATE TABLE IF NOT EXISTS aikaraoke_song_versions (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    SONG_ID INT(18) NOT NULL,
    VERSION_TYPE VARCHAR(255) DEFAULT 'original',
    STORAGE_PATH VARCHAR(255) NOT NULL,
    METADATA TEXT DEFAULT NULL,
    DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX IX_AIKARAOKE_SONG_ID (SONG_ID),
    FOREIGN KEY (SONG_ID) REFERENCES aikaraoke_songs(ID) ON DELETE CASCADE
);

-- Таблица текстов песен с разметкой
CREATE TABLE IF NOT EXISTS aikaraoke_lyrics (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    SONG_ID INT(18) NOT NULL,
    LINE_NUMBER INT(11) NOT NULL,
    TEXT TEXT NOT NULL,
    START_TIME FLOAT NOT NULL,
    END_TIME FLOAT NOT NULL,
    DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX IX_AIKARAOKE_SONG_ID (SONG_ID),
    FOREIGN KEY (SONG_ID) REFERENCES aikaraoke_songs(ID) ON DELETE CASCADE
);

-- Таблица сгенерированных видеороликов
CREATE TABLE IF NOT EXISTS aikaraoke_videos (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    SONG_ID INT(18) NOT NULL,
    USER_ID INT(18) NOT NULL,
    STORAGE_PATH VARCHAR(255) NOT NULL,
    VIDEO_STYLE VARCHAR(100) DEFAULT 'default',
    STATUS VARCHAR(255) DEFAULT 'processing',
    DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_COMPLETED TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX IX_AIKARAOKE_SONG_ID (SONG_ID),
    INDEX IX_AIKARAOKE_USER_ID (USER_ID),
    FOREIGN KEY (SONG_ID) REFERENCES aikaraoke_songs(ID) ON DELETE CASCADE
);

-- Таблица караоке-сессий (попыток пения)
CREATE TABLE IF NOT EXISTS aikaraoke_sessions (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    USER_ID INT(18) NOT NULL,
    SONG_ID INT(18) NOT NULL,
    VIDEO_ID INT(18) DEFAULT NULL,
    AUDIO_RECORDING_PATH VARCHAR(255) DEFAULT NULL,
    SCORE INT(11) DEFAULT NULL,
    ACCURACY_PERCENT FLOAT DEFAULT NULL,
    DATE_STARTED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_COMPLETED TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX IX_AIKARAOKE_USER_ID (USER_ID),
    INDEX IX_AIKARAOKE_SONG_ID (SONG_ID),
    INDEX IX_AIKARAOKE_VIDEO_ID (VIDEO_ID),
    FOREIGN KEY (SONG_ID) REFERENCES aikaraoke_songs(ID) ON DELETE CASCADE,
    FOREIGN KEY (VIDEO_ID) REFERENCES aikaraoke_videos(ID) ON DELETE SET NULL
);

-- Таблица детализированных результатов караоке-сессии
CREATE TABLE IF NOT EXISTS aikaraoke_session_details (
    ID INT(18) NOT NULL AUTO_INCREMENT,
    SESSION_ID INT(18) NOT NULL,
    LYRIC_ID INT(18) NOT NULL,
    SCORE INT(11) DEFAULT NULL,
    ACCURACY_PERCENT FLOAT DEFAULT NULL,
    NOTES TEXT DEFAULT NULL,
    PRIMARY KEY (ID),
    INDEX IX_AIKARAOKE_SESSION_ID (SESSION_ID),
    INDEX IX_AIKARAOKE_LYRIC_ID (LYRIC_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES aikaraoke_sessions(ID) ON DELETE CASCADE,
    FOREIGN KEY (LYRIC_ID) REFERENCES aikaraoke_lyrics(ID) ON DELETE CASCADE
);
